### ISSUE TITLE
JS-only 360degree car demo

### ISSUE THREAD

**Issue by vilav** [naver/egjs-persist#18]
Hi 

The 360-degree demo on egjs is one of the most performant ones of any JS library out there. Is there a demo / reference of the 360-degree code without a JQuery dependency?

**Comment by sculove** [comment]
@vilav Are you saying this?
https://naver.github.io/egjs-axes/#car-360º-viewer

the egjs-axes don't use jQuery.

**Comment by vilav** [comment]
@sculove Yup, if i click on the Codepen link below the demo, it shows JQuery in the JS resources. Didn't seem to work without it. Sorry if I missed something there...

<img width="862" alt="screenshot 2017-09-25 22 34 17" src="https://user-images.githubusercontent.com/849098/30814068-be156ad6-a241-11e7-91fa-958e9a662340.png">

**Comment by sculove** [comment]
@vilav jquery is just used for domready.
It is not related to egjs-axes.

Look at this example.
https://codepen.io/sculove/pen/Bwpjva

**Comment by vilav** [comment]
Thanks @sculove! This is awesome
In that demo, is there a way to attach a HTML range slider such that when you move the range slider the corresponding visual sequence moves as well? Something similar to this: https://codepen.io/GreenSock/pen/dNjYeM
