### ISSUE TITLE
Remove useless page state(information)

### ISSUE THREAD

**Issue by jongmoon** [naver/egjs-persist#33]
I am using the state save / restore module to restore the state like BFCache provided by Safari. However, there is an issue that uses space unnecessarily. I have tried to solve this problem, but I am not satisfied with it.

## Overview and Problems of Current Modules

We have created a module to remember the previous state when moving to the previous or next page in the history of the page.

This feature is one of the functions that are required quite a lot in the multiple page based service. That is, when you press the Back button or the Forward button, you want to restore the previous state to improve usability. For example, the scroll position is the most representative state. In addition, the position of the carousel shown in the page can also be restored. In the Safari browser, BFCache provides this functionality.

On the PC, Android Chrome, the Back button does not restore the previous page when you go to the previous page by pressing the Back button, so you can use this module (internally using session storage) to save the state to be restored on the page, When you return to the page, it recalls the saved state.

However, the current implementation is a big problem. As you move through the page, the stored status values will not be deleted and will continue to accumulate. Because there is a limit to the storage space (2MB ~ 10MB), there is an issue that exceeds the storage space.

### AS IS
![image](https://user-images.githubusercontent.com/3255471/51522901-c95b8e80-1e6d-11e9-9122-8cf72c862713.png)

### TO BE
  - When the page is moved, unnecessary storage information is deleted based on the current page.

![image](https://user-images.githubusercontent.com/3255471/51522919-d4162380-1e6d-11e9-9950-5f3dfe9481b6.png)

## Difficulty in solving problems

To solve this problem, a method for deleting unnecessary data is required.

To eliminate unnecessary state values, the method you want to implement is as follows.

Removes the status of unnecessary pages from the session storage when the previously moved pages are excluded from the target to move back or forward based on the current page. For example, if you move from A page to B page and then back to C page again, page B is not available for Back or Forward. Therefore, the status information of the page is cleared.

This implementation maps the depth information to each page movement path. If the depth of the newly moved page is less than or equal to the existing page depth, existing page information existing below the depth is deleted.

**However, I encounter some difficulties.**
   1. No Browser API to know depth information
   2. Can not use or update history state information
       - history.state can be overwritten arbitrarily on each page
   3. The history length that will be the basis of the depth value is maximum length is 50 (based on Chrome).
   4. Can not distinguish whether navigation is Back or Forward.
   5. Long press on the Back / Forward button, as well as previous page navigation, allows you to skip several steps.

## Incomplete alternative

So I thought about how to calculate the virtual depth based on the page URL.

That is, we add depth every time we move to a new page. For example, if you move in the order of A -> B -> C, you can randomly assign depths of 1, 2, and 3, respectively.

**However, this alternative also faces two problems:**

   1. A -> B -> C -> A (each moved to a new page), A state value will be overwritten.
   2. A -> B -> C -> A -> D (each moved to new page) You can not know the depth of current A(1st or 4th) if you move the steps through the long press of the Back button.

> History.state cannot be used

In this situation, it is possible to compensate in the following way, but it is not a perfect solution either.
      - You can complement the history length value by creating a key for each page in combination with a URL, but if you go beyond 50, the same problem occurs.
      - The possibility of duplication can not be avoided even though the key to the page is combined with the URL to Referrer.

I am currently working on the issue above, but I would like to ask you further advice.

**Comment by younkue** [comment]
#34 

In case of ```A -> B -> C -> A(back) -> D```, do not clear B or C at this time. However, the function I added is to add D by clearing B and C. ```A -> B(X) -> C(X) -> A(back) -> D, B(X), C(X)```

In cases like ```A -> B -> C -> A```, it is difficult to preserve the previous A.
Instead, you can achieve the same depth as ```B -> C -> A``` by deleting the previous A.

Management with length is a problematic option because only 50 are maintained.
If there are more than 50 length, all of the urls in the depth array will have problems.
